global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_metrics_prom'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.2:8080']